

services:
  app:
    user: "www-data"
    build:
      context: .
      dockerfile: Dockerfile
    image: laravelpj
    environment:
      - TZ=Asia/Ho_Chi_Minh
    container_name: laravelpj
    volumes:
      - .:/var/www:cached
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    environment:
      - TZ=Asia/Ho_Chi_Minh
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  
    networks:
      - laravel-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravelpj
    ports:
      - "3307:3306"
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge